[package]
name = "krpc_mars"
version = "0.7.0"
authors = ["bartslinger", "cahu"]
build = "build.rs"
license = "GPL-3.0"
edition = "2021"

[dependencies]
protobuf = "2.0"

[build-dependencies]
protoc-rust = "2.0"
